version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db_v3
    env_file: ".env"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bot_db
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: bot_app
    depends_on:
      - db
    env_file: ".env"
    ports:
      - "8002:8000"

volumes:
  db_data:
